### ISSUE TITLE
What's the difference between f1_test and f1 in main.py file?

### ISSUE THREAD

**Issue by PrivateThink** [giahy2507/MATEPC#1]
Thank you for your open source，I have some doubts. in main.py file some codes as follows：

print("F1 test, ATEPC task: ", f1_test)
f1, acc = atepc_evaluator.evaluate(ys_true, ys_pred, verbose=True)

What's the difference between f1_test and f1？
f1, and acc are the final results of the model MATEPC?

**Comment by giahy2507** [comment]
"f1_test" is the performance of the join model (MATEPC) in the joint task (ATEPC) that evaluate on 7 labels (B_pos, I_pos, B_neu, I_neu, B_neg, I_neg, and O).

Whereas, "f1" and "acc" is the F1-score and Accuracy for the joint model in the separated task, ATE and APC respectively. These scores are the final results of the model MATEPC.

**Comment by PrivateThink** [comment]
Thank you for your answers. Your research is excellent.

**Comment by PrivateThink** [comment]
Is the w2v.150.word.txt file used for both restaurant and laptop datasets?

**Comment by giahy2507** [comment]
yes
